// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOcopv_7XaCQ8re4ypwmwuh7WAtquKURs',
    appId: '1:12598595372:web:fadca9ece9c930f2d66689',
    messagingSenderId: '12598595372',
    projectId: 'barong-xtrade',
    authDomain: 'barong-xtrade.firebaseapp.com',
    storageBucket: 'barong-xtrade.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAwR0vnhFx_67e6gCuMMHnI1XxHd-lYnI',
    appId: '1:12598595372:android:4ddaded7a43f09ccd66689',
    messagingSenderId: '12598595372',
    projectId: 'barong-xtrade',
    storageBucket: 'barong-xtrade.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGmG-99q17BB7lsvCJTEThw0sDX14_Ls4',
    appId: '1:12598595372:ios:6bad64102a9871b6d66689',
    messagingSenderId: '12598595372',
    projectId: 'barong-xtrade',
    storageBucket: 'barong-xtrade.appspot.com',
    iosClientId: '12598595372-kiio04425bjggekclilnabh6ckl5fs4f.apps.googleusercontent.com',
    iosBundleId: 'com.barongxtrade.barongxtrade',
  );
}
